### ISSUE TITLE
Замена текста захватывает часть прошлого ввода

### ISSUE THREAD

**Issue by antonsoroko** [freemind001/easy-switcher#1]
в браузере нажать ctrl+t для открытия новой вкладки и написать `руддщ` потом сделать коррекцию и получится:
`thello`

к консоли ctrl+c или ctrl+w и потом написать что-то, а потом сделать коррекцию - и начинается "расколбас" :-)

похоже что замена текста захватывает часть прошлого ввода.

**Comment by freemind001** [comment]
принято, поправлю

**Comment by antonsoroko** [comment]
ещё момент: enter почему-то не считается программой как разделитель слов, соотв при переключении такого текста:
```
ааааа.
пппп.
рррр.
```

будет замена всех 3 строк (`reverse-mode=false` если что.)

**Comment by freemind001** [comment]
исправлено

**Comment by antonsoroko** [comment]
@freemind001 
прошлые проблемы ушли, спасибо!

но есть одна маленькая новая:

в консоли:
```
$ ghbdtn<F12>
```
получаем
```
$ gпривет
```

(<F12> - клавиша для коррекции.)

**Comment by freemind001** [comment]
Нажатия F1-12 игнорируются, т.к. в обычной жизни они не вводят текст и конверитровать их не надо.
А по F12 в терминал прилетает ~. 
Если следить за этим и еще один BkSp добавить по нажатию F12, то в обычных окнах лишний символ удаляться будет. 
Хз что с этим делать, пока так оставлю. ES не следит в какое окно ввод идет, только за вводом с клавиатуры.

**Comment by antonsoroko** [comment]
>А по F12 в терминал прилетает ~.

ах точно. теперь ясно почему так происходит.
ну это минорная проблема, так что можно забить.
спасибо.
