### ISSUE TITLE
easy-switcher doesn't work at all

### ISSUE THREAD

**Issue by georgehazan** [freemind001/easy-switcher#5]
1. when I click LeftCtrl, the keyboard layout isn't switched. That's what I see in -d mode:

```
input LEFTCTRL down
input LEFTCTRL up
buffer cleared
```

2. When I click Pause, the printed text is cleared using BS, but then is restored back without any changes.

```
input A down
input A up
input B down
input B up
input C down
input C up
input PAUSE down
input PAUSE up
prepare buffer
 raw: A down; A up; B down; B up; C down; C up; PAUSE down; PAUSE up; 
 prepared: A down; A up; B down; B up; C down; C up; 
convert word
output BACKSPACE down
output BACKSPACE up
output BACKSPACE down
output BACKSPACE up
output BACKSPACE down
output BACKSPACE up
output LEFTCTRL down
output LEFTCTRL up
output A down
output A up
output B down
output B up
output C down
output C up
```

Kubuntu 24.04.01, latest easy-switcher binaries. Config is attached below
[conf.zip](https://github.com/user-attachments/files/17042906/conf.zip)

**Comment by freemind001** [comment]
please try to use other key or combination of keys to switch layout in your system settings.
you can configure additional key to switch layout in your system, if you want to keep ctrl for manual change of layout. 
ctrl and alt keys clear internal buffer of easy switcher to avoid messy output during convertation, after typing shortcuts (e.g. ctrl+c, ctrl+v, ctrl+t and so on)

**Comment by georgehazan** [comment]
> please try to use other key or combination of keys to switch layout in your system settings.

I've tried many combinations (real keys, functional keys, virtual keys like Pause), but nothing helps. In all cases the behavior is the same: easy-switcher kinda doesn't know about eng / rus keyboard layout and simply ignores switching from one layout to another.

Also, I'm under 24.10 now + Wayland, but it brought no difference.

**Comment by freemind001** [comment]
this part erases your input:
output BACKSPACE down
output BACKSPACE up
output BACKSPACE down
output BACKSPACE up
output BACKSPACE down
output BACKSPACE up

this part should change your layout:
output LEFTCTRL down
output LEFTCTRL up

this part writes your input back:
output A down
output A up
output B down
output B up
output C down
output C up

this behavior is correct. Your system should change layout when pressing left ctrl.
is layout changed when you press left ctrl? (without easy switcher running)

**Comment by georgehazan** [comment]
> this behavior is correct. Your system should change layout when pressing left ctrl.
> is layout changed when you press left ctrl? (without easy switcher running)

no, it's not. If I switch the layout manually when easy-switcher removes & re-inserts those symbols, everything got inserted in the right language, but the miracle of automatic layout switch never happens

**Comment by freemind001** [comment]
what key do you use to switch the layout manually?

**Comment by georgehazan** [comment]
> Config is attached below
> [conf.zip](https://github.com/user-attachments/files/17042906/conf.zip)

config is here. typically I use LeftCtrl to switch languages manually & Pause to revert the last entered string

**Comment by freemind001** [comment]
У вас есть системная комбинация клавиш, которая меняет раскладку, она указывается в настройках убунту, и работает вне заависимости от easy-switcher'a
Её и надо прописать в конфиг свитчера. 
Судя по debug сообщениям, программа работает корректно, переключение раскладки должно происходить при 
output LEFTCTRL down
output LEFTCTRL up

Для этого left ctrl должен быть прописан в настройках ос

**Comment by georgehazan** [comment]
> У вас есть системная комбинация клавиш, которая меняет раскладку, она указывается в настройках убунту, и работает вне заависимости от easy-switcher'a

Я не могу туда прописать LeftCtrl, потому что иначе он вообще вырубится как Ctrl, а будет только переключать языки... Сейчас в качестве системной кнопки для переключения языков используется CapsLock

**Comment by georgehazan** [comment]
Ещё почему-то замена символов при нажатии Pause происходит ужасно медленно... порядка 2 секунд занимает убрать и вставить символы заново

**Comment by georgehazan** [comment]
Ок, я понял, вторую самостоятельную кнопку на переключение раскладок повесить не удастся... Печалька

**Comment by freemind001** [comment]
> Сейчас в качестве системной кнопки для переключения языков используется CapsLock

пропишите тогда капс в easy switcher, что мешает то
layout-switch-key=58

**Comment by georgehazan** [comment]
> пропишите тогда капс в easy switcher, что мешает то

хотелось левый контрол, потому что им всю жизнь переключал русский 😁
